- components/HomePage.tsx
- components/HtanNavbar.tsx
- package.json
- styles/app.css
- yarn.lock
- Align breadcrumbs
- Add columns to data release page
- Add wordpress API calls to homepage cards 
- Add wordpress API calls for homepage hero splash text
- Add link on homepage "Explore" button to point to data release page 
- Add link in navbar to HTAN main site
> Address issues

- data/data.json
Note: 
- data for centerA is the same as the one for centerB - testing structure only.
- biospecimen is populated with patient demographics actually (haven't ingested biospecimen data yet)
We can review and decide how to proceed next - various adjustments are possible.
> Updated with notional data for two notional centers

- components/Atlas.tsx
- components/AtlasDataTable.tsx
- styles/app.scss
- Add horizontal scrollbar for tables
- Add column select to allow user to add/remove columns
> Col width updates 

- data/data.json
Added sc fake metadata; fixed center IDs; fixed entity IDs to use center namespace;
Addresses
#47 #38 #42 (#51 - partially)
> Updated json data

- components/HomePage.tsx
- styles/app.scss
> play around with style

- lib/helpers.ts
- package.json
- pages/explore.tsx
- yarn.lock
Only uses placeholder for now.
Related to #77
> Add loading indicator while data is fetched in explore page

- components/FilterPanel/FilterPanel.tsx
- components/FilterPanel/styles.module.scss
- lib/helpers.ts
- pages/explore.tsx
(1) Make more dropdowns use checkbox menu instead of Select
(2) Make other dropdowns close when you click on another one
(3) Make dropdowns smaller and open underneath the button
> Dropdown improvements on Explore page

- lib/helpers.ts
Fixes https://github.com/ncihtan/htan-portal/issues/89
> Dont stratify assay types by level, since level can be filtered in another menu

- components/filter/FileTable.tsx
- pages/explore.tsx
> Make file table download functional

- components/HomePage.tsx
- lib/helpers.ts
- pages/explore.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/82
> Dynamically calculate homepage stats based on data

- components/ExploreTabs.tsx
- components/WPAtlasTable.tsx
Add atlas id to table, and make atlas the default tab
> Atlas fixes

- next.config.js
- package.json
- yarn.lock
See https://github.com/vercel/next.js/issues/12735#issuecomment-629404102
> Enable type checking in dev mode

- components/FilterPanel/FilterCheckList.tsx
- components/filter/Filter.tsx
- components/filter/FilterControls.tsx
- lib/types.ts
- pages/explore.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/98
Fixes bug " Removing filters by clicking on the group name doesn't work"
Adds button to clear all filters
> Fix issues with filtering

- components/ExploreSummary.tsx
- components/FileTable.tsx
- pages/explore.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/105
> Move explore summary from file tab to above the tabs

- lib/helpers.ts
Fixes https://github.com/ncihtan/htan-portal/issues/117
> Fix issues in explore page with filters

- components/FileTable.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/116
> Fix for "Make it easier to search for a single patient id"

- components/DataReleasePage.tsx
- components/HomePage.tsx
- components/WPAtlasTable.tsx
- components/filter/AtlasTable.tsx
- components/filter/FilterControls.tsx
- lib/filterHelpers.ts
- lib/helpers.ts
- pages/atlas/[id].tsx
- pages/explore.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/115
(1) Add "back" and "view files" buttons
(2) Remove all except first three tabs
> Atlas page adjustments

- ApiUtil.ts
- components/DataSchema.tsx
- components/DataStandard.tsx
- components/ExpandableText.tsx
- components/expandableText.module.scss
- lib/dataSchemaHelpers.ts
- lib/dataTableHelpers.ts
- package.json
- pages/data_releases.tsx
- pages/index.tsx
- pages/single_cell.tsx
- pages/standard/biospecimen.tsx
- pages/standard/bulkdnaseq.tsx
- pages/standard/bulkrnaseq.tsx
- pages/standard/clinical.tsx
- pages/standard/design.tsx
- pages/standard/imaging.tsx
- pages/standard/rnaseq.tsx
- pages/standard/scatacseq.tsx
- pages/standards.tsx
- pages/tools.tsx
- pages/transfer.tsx
- yarn.lock
Fix #104
Proof of concept visualization as nested tables for each data schema:
> Add DataSchema

- components/WPAtlasTable.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/114
> Use proper atlas id in Atlases explore table

- components/WPAtlasTable.tsx
> Switch atlas table column order

- components/ExploreSummary.tsx
- styles/app.scss
> Improve Files table summary statistics

- components/FileTable.tsx
Fix #135
Also, related to #133
> Replace atlas with atlas id in file table

- components/ExploreTabs.tsx
> Pluralize Biospecimen tab name

- components/FileTable.tsx
- lib/helpers.ts
> Display synapse id in the download popup

- components/FileTable.tsx
- lib/helpers.ts
- package.json
Fix #129
Synapse link is still missing. Need to merge #134 which exposes the `synapseId` field.
> Truncate filename column

- components/HomePage.tsx
Fix #153
See https://stackoverflow.com/a/53074436
> Fix use effect infinite loop

- components/ExploreTabs.tsx
- lib/helpers.ts
- pages/atlas/[id].tsx
- pages/explore.tsx
> atlas page - remove back button and fix view files button

- components/HomePage.tsx
- lib/helpers.ts
- pages/index.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/145
> load synapse data on homepage in getStatic handler

- lib/helpers.ts
Time between loader appearing and UI appearing is down to ~1.8s from ~5.3s
> Optimize explore page

- components/FileTable.tsx
- components/filter/FilterControls.tsx
- lib/helpers.ts
- lib/types.ts
(1) Group together all levels of a single assay type
(2) Dont capitalize scRNA
> Changes related to handle assay types

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
- components/ColumnSelect.tsx
- components/DataTableControls.tsx
- components/EnhancedDataTable.tsx
- components/FileTable.tsx
- components/WPAtlasTable.tsx
- lib/dataTableHelpers.tsx
Fix #181
Fix #187
- Implementation mostly copied form cBioPortal. Seems like it is tricky at the moment to directly use cBioPortal packages due to server side rendering errors.
- ~~Search UI is not functional yet. Will be addressed in a separate PR.~~ Needed to address this in this PR as well due to a conflict
> Allow what columns are visible 

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
> Remove download buttons from Cases and BioSpecimens tab

- components/FileTable.tsx
- lib/helpers.ts
> Add download instructions for level 1 and level 2 data

- data/get_syn_data.py
This handles the case where column order might differ in the data files.
Instead always use the column order as defined by the schema and add
empty values whenever the columns are missing. One thing to note: we use
the component's dependencies to determine what columns should be
included. Not sure if this includes both required + optional columns,
occasionally there seem to be some columns in the manifest that are not
in the schema. The current logic excludes those
This issue was originally discovered in File Type dropdown
These HTA3 ones should actually be fastq files, see e.g. after filtering:
Not sure exactly why the fastq files count goes down, but the problematic ones for HTA3 are converted to fastq now:
> Fix #170 File format

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
- components/WPAtlasTable.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/163
> add default sort for explore page tables

- components/ExploreTabs.tsx
- components/WPAtlasTable.tsx
- pages/explore.tsx
- Atlas Filter is synced with the checkboxes.
- View files button is not functional yet.
Fix #193
> Add checkboxes to Atlas Table

- lib/filterHelpers.ts
Fixes https://github.com/ncihtan/htan-portal/issues/207
I must have been tired that day... I totally forgot to use one of the arguments to the function 😆
> Fix bug in filter count calculation

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
- components/FileTable.tsx
- lib/dataTableHelpers.tsx
> Fix data table custom sort functionality

- components/ColumnSelect.tsx
- components/DataTableControls.tsx
- components/EnhancedDataTable.tsx
- lib/dataTableHelpers.tsx
> Improve column visibility implementation

- lib/helpers.ts
Fixes https://github.com/ncihtan/htan-portal/issues/215
@alisman I guess the data is no longer messed up?
> Remove block on certain files

- components/WPAtlasTable.tsx
- lib/helpers.ts
Fixes https://github.com/ncihtan/htan-portal/issues/205
> Add # cases and # biospecimens columns to atlas table

- components/ExploreSummary.tsx
- missing.d.ts
- package.json
- yarn.lock
> Use singular form of words when count is 1

- components/filter/FilterControls.tsx
- lib/types.ts
- styles/app.scss
Fixes https://github.com/ncihtan/htan-portal/issues/223
Fixes https://github.com/ncihtan/htan-portal/issues/224
> Changes to filter controls

- components/CaseTable.tsx
- lib/helpers.ts
> Convert age in days to years

- components/ExploreSummary.tsx
> Fix assay count

- components/FileTable.tsx
- components/SimpleScrollPane.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/196
> Improve visualization of long lists of biospecimens in FileTable

- lib/helpers.ts
> Fix imaging assay types

- components/ExploreSummary.tsx
> Fix off-by-one issue in explore summary counts

- components/WPAtlasTable.tsx
- lib/getAtlasMetaData.ts
Fixes https://github.com/ncihtan/htan-portal/issues/212#event-4558326435
> Add metadata download to atlas table

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
- components/DataStandard.tsx
- components/ExploreTabs.tsx
- lib/dataSchemaHelpers.ts
- lib/dataTableHelpers.tsx
- lib/types.ts
- pages/explore.tsx
- pages/standard/biospecimen.tsx
- pages/standard/bulkdnaseq.tsx
- pages/standard/bulkrnaseq.tsx
- pages/standard/clinical.tsx
- pages/standard/imaging.tsx
- pages/standard/rnaseq.tsx
- pages/standard/scatacseq.tsx
> Generate columns by data schema

- components/filter/FilterControls.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/243
> Sort filter options

- components/WPAtlasTable.tsx
Fixes  https://github.com/ncihtan/htan-portal/issues/250
> sort atlas metadata download modal

- lib/dataTableHelpers.tsx
> Remove duplicate dependencies

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
- components/ColumnSelect.tsx
- components/EnhancedDataTable.tsx
- lib/dataTableHelpers.tsx
> Add tooltip for column headers

- lib/dataSchemaHelpers.ts
- pages/standard/clinical.tsx
> Add missing clinical data standards

- components/BiospecimenTable.tsx
- components/CaseTable.tsx
- lib/dataTableHelpers.tsx
- lib/helpers.ts
- pages/explore.tsx
> Add Demographics to the Cases table

- components/FileTable.tsx
> Increase filename col size

- components/DataSchema.tsx
> Override bulk WES with bulk DNA

- components/CaseTable.tsx
- components/WPAtlasTable.tsx
- lib/dataSchemaHelpers.ts
- lib/dataTableHelpers.tsx
- styles/app.scss
> Adjust numerical columns to the right

- components/WPAtlasTable.tsx
- data/minerva-story-mappings.json
This is a temporary solution to point to the already existing Minerva
Stories. Once properly submitted we can host them from our own domain.
> Add HMS Minerva Stories

- components/ExploreSummary.tsx
- components/ExploreTabs.tsx
- components/filter/FilterControls.tsx
- lib/helpers.ts
- lib/types.ts
- package.json
- pages/explore.tsx
- styles/app.scss
EDI working group asked for easy access to demographic related numbers, so added another filter
> add demographics filter

- components/ColumnSelect.tsx
- components/EnhancedDataTable.tsx
- components/FileTable.tsx
- lib/fileTableHelpers.tsx
- lib/helpers.ts
Fixes https://github.com/ncihtan/htan-portal/issues/320
> Add "Details" modal to FileTable to highlight and interact with hidden columns

- components/ExploreTabs.tsx
- components/WPAtlasTable.tsx
- lib/filterHelpers.ts
- lib/helpers.ts
- pages/explore.tsx
Fixes https://github.com/ncihtan/htan-portal/issues/319
> Show filtered case and sample counts in atlas table

- components/FileTable.tsx
- components/common.module.scss
Fixes https://github.com/ncihtan/htan-portal/issues/328
> Fix styling issue in view details modal when entries are too long

- data/get_syn_data.py
- data/syn_metadata.json
A quick fix to add new CHOP data
> Add CHOP last minute ScATACSeq data + updates for manuscript revision

- data/imaging-thumbnail-mappings.json
Add some thumbnails for washu imc data
> Add washu imc thumbnails

- components/FileTable.tsx
- styles/app.scss
> Add miniature reference in tooltip

- components/FileTable.tsx
Enable this for production, remove the previously required URL parameter
> enable thumbnails

- data/get_syn_data.py
- data/processSynapseJSON.ts
- data/syn_metadata.json
- next-env.d.ts
> Add initial release 2 data

- next.config.js
- package.json
- yarn.lock
Having issues building production, even though it works fine for PRs. Figured maybe upgrading Next might help
> upgrade to nextjs 12.1

- pages/static/publications.html
We will have to come up with a more automated way to generate this page based on biorxiv and pubmed ids
> update colorectal cancer paper (biorxiv->cell)

- components/DataTableControls.tsx
- components/EnhancedDataTable.tsx
- components/FileTable.tsx
- components/LevelSelect.tsx
Add level filter dropdown on publication page
For example:
https://htan-portal-nextjs-git-fork-leexgh-level-filter-htan.vercel.app/publications/chop_all_chen_2022?tab=scrna-seq
> Add level filter on publications page files tab

- components/DataSchema.tsx
- lib/dataSchemaHelpers.ts
- lib/dataTableHelpers.tsx
- lib/publications.ts
- pages/explore.tsx
> Resolve optional dependencies for data standards page

- pages/standards.tsx
Related to the Github issue here: https://github.com/Sage-Bionetworks/schematic/issues/1013
> Added schema viz link and link-out icon

- data/htan-imaging-assets.json
Includes new imaging assets for release 3 where available and removes previously broken assets
> Update imaging assets

- components/WPAtlasTable.tsx
- components/filter/FilterControls.tsx
- data/processSynapseJSON.ts
- lib/helpers.ts
- lib/types.ts
Enable a release filter by adding the `?qc` parameter
> Add hidden release filter for QC'ing purposes

- data/htan-imaging-assets.json
This PR adds new H&E thumbnails that were previously missing for WASHU
> Add further H&E thumbnails

- data/htan-imaging-assets.json
Merging this into another branch of imaging asset updates to check that they all deploy correctly.
> Adds more Duke HE assets that previously failed

- pages/static/data-access.html
> Add dbgap Accession and link

- components/common.module.scss
> Increase max width of view details modal

- components/ToolTable.tsx
- data/tools_custom.json
- lib/helpers.ts
- lib/types.ts
> Allow multiple publication links in a single column

- components/DataSchema.tsx
- components/ValidValues.tsx
> Add modal to show all valid values

- lib/dataSchemaHelpers.ts
- lib/vcsHelpers.ts
- package.json
- pages/standards.tsx
- yarn.lock
> Dynamically fetch the data model from the latest GitHub release

- pages/transfer.tsx
Fix https://github.com/ncihtan/htan-portal/issues/525
> Change ingress docs link

- components/FileTable.tsx
> Set download location for files with identical names

- pages/static/resources.html
Adds a new section for recordings, see https://htan-portal-nextjs-88zk3pje6-htan.vercel.app/resources:
> Add F2F recordings to resource page

- components/ExploreTabs.tsx
- components/HomePage.tsx
- components/Plots.tsx
> Make plots tab text customizable

- pages/_middleware.js
Fix https://github.com/ncihtan/htan-portal/issues/554
> make url lower to uppercase conversion more stringent

- data/processSynapseJSON.ts
- remove `dbgap_release_all.json` and `dbgap_img_release2.json` dependency
- get the information from `entities_v4.csv` instead
Related to #534
> use entities_v4 file to get dbgap release info

- components/FileTable.tsx
> Do not show IDC link for the image viewer

- pages/standards.tsx
there current one seems to be broken - we can bring it back when it's working again
> remove schema vis

- packages/data-portal-commons/src/lib/entityReportHelpers.ts
- packages/data-portal-explore/src/components/ExplorePlot.tsx
> Fix broken Plots tab

- .gitignore
- README.md
- lib/helpers.ts
- package.json
- packages/data-portal-explore/src/components/AtlasTable.tsx
- packages/data-portal-explore/src/components/Explore.tsx
- packages/data-portal-explore/src/components/ExploreTabs.tsx
- pages/explore.tsx
> Update metadata url to aws s3 bucket

- packages/data-portal-explore/package.json
- packages/data-portal-explore/src/components/FileTable.tsx
> Add download manifest button for CDS level 1 and 2 sequencing data

- packages/data-portal-table/src/components/EnhancedDataTable.tsx
> Fix the new line issue with the table metadata download

- packages/data-portal-explore/src/components/FileTable.tsx
> Show Coming Soon message for only imaging level 2 files

- packages/data-portal-explore/src/components/FileTable.tsx
> Include coming soon in the not downloadable files list

- packages/data-portal-schema/src/lib/dataSchemaHelpers.ts
> Fix an infinite loop issue with findAllAncestors

- packages/data-portal-explore/src/components/FileTable.tsx
Related to #620 and #632.
We can probably close #620 after merging this PR.
> Link out to synapse regardless of level

- data/processSynapseJSON.log
- data/processSynapseJSON.ts
- lib/helpers.ts
- packages/data-portal-commons/src/lib/entity.ts
- packages/data-portal-commons/src/lib/entityReportHelpers.ts
- packages/data-portal-commons/src/lib/fillInEntities.ts
- packages/data-portal-commons/src/lib/getCaseValues.ts
- packages/data-portal-commons/src/lib/types.ts
- packages/data-portal-explore/src/components/CaseTable.tsx
- packages/data-portal-explore/src/components/FileFilterControls.tsx
- packages/data-portal-explore/src/components/FileTable.tsx
- packages/data-portal-utils/src/lib/types.ts
Fixing #625 
Describe changes proposed in this pull request:
Screenshot:
Notify reviewers:
@onursumer
> ✨New Feature: Treatment Filter

- components/PreReleaseBanner.tsx
- pages/static/events.html
- pages/static/jamboree-2023.html
- pages/static/jamboree.html
> Add jamboree 2024 registration

- packages/data-portal-explore/src/components/DataAvailabilityTable.tsx
Customize data overview table for hta1_2024_pdf_johanna-klughammer, show `TBD` for:
- CODEX unknown level
- ExSEQ unknown level
- MERFISH unknown level
- Slide-seq V2 unknown level
> Customize TBD for hta1_2024_pdf_johanna-klughammer data overview table

- data/tools_custom.json
> Add GRAPE-Net tool

- components/Plots.tsx
- lib/helpers.ts
- packages/data-portal-commons/src/lib/entityReportHelpers.ts
Fix #681
TODO: Biopsecimen count still does not match
> Improve organ and case counts displayed on the homepage

- packages/data-portal-schema/src/lib/dataSchemaHelpers.ts
- pages/standard/mass_spectrometry.tsx
- pages/standards.tsx
> Add mass spectrometry data standard

- components/DataSchema.tsx
- components/DataStandard.tsx
> Use grow instead of min width

- packages/data-portal-explore/src/lib/helpers.ts
> Exclude Not Reported when counting organs for summary

- components/PreReleaseBanner.tsx
> add nature collection banner

- components/DataSchema.tsx
> Fix empty Manifest Names column download content

- pages/static/resources.html
> Remove policy documents

- packages/data-portal-schema/src/lib/dataSchemaHelpers.ts
- pages/standard/spatial_transcriptomics.tsx
Fix #698
TODO: MERFISH not pulled in yet.
> Add missing spatial transcriptomics manifests

- components/DataSchema.tsx
- components/DataStandard.tsx
- components/DataStandardsDirections.tsx
- pages/transfer.tsx
- styles/app.scss
> Add data standards directions, and update data submission link

- components/HtanNavbar.tsx
> Add newsletter link

- data/tools_custom.json
> Add CSPOT tool

- next.config.js
- packages/data-portal-commons/src/components/AtlasDescription.tsx
Fix #736
Redirect preview:
- https://htan-portal-nextjs-git-fork-onursumer-fix-broken-ph-5f19f7-htan.vercel.app/hta8
- https://htan-portal-nextjs-git-fork-onursumer-fix-broken-ph-5f19f7-htan.vercel.app/htan-dcc
> Fix broken phase 1 center URLs

- components/PageWrapper.tsx
- package.json
- packages/data-portal-commons/package.json
- packages/data-portal-explore/package.json
- packages/data-portal-filter/package.json
- packages/data-portal-table/package.json
- pages/index.tsx
- yarn.lock
Fix #743 
See https://stackoverflow.com/questions/56334381/why-my-font-awesome-icons-are-being-displayed-big-at-first-and-then-updated-to-t
Compare https://humantumoratlas.org/standard/clinical to https://htan-portal-nextjs-git-fork-onursumer-update-fortaw-8bb9fb-htan.vercel.app/standard/clinical
> Fix fort awesome lib styling issue

- components/PublicationTabs.tsx
- pages/publications/[id].tsx
> Fix broken publication tabs

- packages/data-portal-commons/src/lib/publicationHelpers.ts
- packages/data-portal-explore/src/components/PublicationTable.tsx
> Fix journal column casing, move date next to journal

- packages/data-portal-explore/src/components/PublicationTable.tsx
> Fix safari date issue

- packages/data-portal-explore/src/components/FileTable.tsx
> Make sure to have the full drs uri

- packages/data-portal-schema/src/lib/dataSchemaHelpers.ts
- pages/standard/spatial_transcriptomics/[[...id]].tsx
> Add 10x Visium spatial transcriptomics RNA-seq level 4 manifest

- packages/data-portal-explore/src/components/PublicationTable.tsx
- packages/data-portal-explore/src/components/exploreTabs.module.scss
> Right align cited by column

- components/HomePage.tsx
- components/HtanNavbar.tsx
> Add How to Cite page

- data/processSynapseJSON.log
- data/publications_manifest_all.json
- lib/helpers.ts
> Update publication data

- README.md
- build_db/client.js
- build_db/main.js
- data/processSynapseJSON.log
- data/processSynapseJSON.ts
- package.json
- packages/data-portal-commons/src/lib/clickhouseHelpers.ts
- packages/data-portal-commons/src/lib/entity.ts
- packages/data-portal-commons/src/lib/fileHelpers.ts
- packages/data-portal-commons/src/lib/getViewerValues.ts
- packages/data-portal-explore/src/components/DataAvailabilityTable.tsx
- packages/data-portal-explore/src/components/FileFilterControls.tsx
- packages/data-portal-explore/src/components/FileTable.tsx
- packages/data-portal-explore/src/components/fileFilterControls.module.scss
- pages/static/data-updates.html
Fix https://github.com/ncihtan/htan-portal/issues/800
TODO:
Notes:
- BIgQuery table still has CDS in the name `released.cds_drs_mapping_V2`, I left that alone for now CC @PozhidayevaDarya
> Rename CRDC-CDS -> CRDC-GC
