ncihtan/htan-portal

- ApiUtil.ts
- components/DataReleasePage.tsx
- components/HomePage.tsx
- pages/data/index.tsx
- pages/index.tsx
- pages/standards/biospecimens.tsx
- pages/standards/cds.tsx
- pages/standards/imaging.tsx
- pages/standards/index.tsx
- pages/standards/rnaseq.tsx
- pages/transfer.tsx
- types.ts
Ethan Cerami mentioned that the "lag" in the UI was something to remove. 
The lag was caused by the remote wordpress API calls happening client side. To remove the lag, I've moved all the API calls server side by wrapping them in `getServerSideProps` on each page. 
There are some other small bug fixes here as well:
- removed extra homepage button, widened hero blurb
- created top level `types.ts` file to reuse type defs
- add footer to data release page
- remove wordpress calls for data release page and hardcode values as per e. cerami request
> Move most wordpress API calls serverside

- data/data.json
Note 
{
"name": "DSA Thumbnail",
"description": "",
"schemaMetadata": { "bonusMetadata": "Yes", "renderType": "dsaThumb" }
}
in imagingData; this indicates the treatment for this attribute (e.g. render thumbnail). Might want to sync up with Dave Gutman on how to render.
I think eventually we will have more structured metadata, so I wouldn't rely on the key "bonusMetadata" to remain in the json blob :)
> Added notional imaging data; removed filename column as necessary

- components/AtlasDataTable.tsx
- data/data.json
- pages/atlas/[id].tsx
- types.ts
- Add ucsc single cell browser to derived data tab
- Fix JSON (values should array of arrays)
see e.g.
https://htan-portal-nextjs-git-fork-inodb-add-ucsc-single-cell-tab.htan.now.sh/atlas/hta2
Future thoughts, can be done in follow up PRs:
- how should we name the datasets, could use synapse id or some other HTAN identifier for the scrnaseq file
Related:
https://github.com/ncihtan/htan-portal/issues/49
https://github.com/ncihtan/htan-portal/issues/46
https://github.com/ncihtan/htan-portal/issues/41
Screenshots:
- Derived data tab in `/atlas/hta2`
- When you click on "View"
> Add ucsc single cell viewer to derived data tab

- components/HomePage.tsx
something like:
Can tweak numbers/style later i guess. I used some palette generator for colors:
> Add dashboard numbers on homepage

- package.json
- pages/explore.tsx
- pages/styles.module.scss
- yarn.lock
We can't use react-spinkit because of this problem https://github.com/vercel/next-plugins/issues/129 (old Github issue but the problem still exists)
> Prettier loading indicator

- lib/helpers.ts
Fixes two points in https://github.com/ncihtan/htan-portal/issues/133:
"Atlas tab id does not match up with files ID"
and
"Undefined shows up in the all filters search"
> Fix off-by-one error in data processing

- components/FileTable.tsx
Was showing as e.g. HTAN VANDERBILT instead of HTAN Vanderbilt
> Fix uppercase on files tab

- data/get_syn_data.py
- data/syn_metadata.json
The metadata JSON contains the synapse ids for the metadata files for
each atlas. Related to #212. Can use links like e.g.
https://www.synapse.org/#!Synapse:syn23636452
FYI: this also excludes TNP atlases atm. We're not showing them anyway so this get rids of some JSON bloat
> Add metadata JSON

- lib/helpers.ts
Fix #225. HTAN Parent ID can be both participant or biospecimen. See also
https://data.humantumoratlas.org/standard/biospecimen
Hard to test right now since we removed HTAPP, but pre-removal this changed fixed it. Seems like it is the only atlas that has biospecimina as children of biospecimina
> Fix case where biospecimen has biospecimen as parent

- lib/gtag.js
- pages/_app.js
- pages/_document.js
Add google analytics. I followed this example: https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics. Account exists in cbioportal analytics account as discussed with @ecerami 
It is not disabled for local development. But maybe that's fine. In their example they set the analytics id as env variable on vercel: https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/lib/gtag.js#L1. For local development it's set as https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/.env.local.example
> Add google analytics

- data/get_syn_data.py
- data/htapp_release1.tsv
- data/syn_metadata.json
We have a list of HTAPP folders to include for release 1. Only include
those files. Add `click` command line interface to easily
include/exclude these folders from the synapse JSON.
> Exclude specific HTAPP folders

- data/get_syn_data.py
- data/syn_metadata.json
- lib/helpers.ts
Fix issues:
- rename all database results to original assay name:
```
python get_syn_data.py && gsed -i 's/"Database Search Result"/"LC-MS3"/g' ../public/syn_data.json && gsed -i 's/"Protein Database"/"LC-MS3"/g' ../public/syn_data.json
```
- handle bug when level 1 file is comma separated (has multiple
biospecimen parents)
> Add stanford atlas

- data/htan-imaging-assets.json
Updates `data/htan-imaging-assets.json` to include initial assets for release 2
> Update HTAN assets for Release 2

- components/FileTable.tsx
- components/PublicationTabs.tsx
Fix: https://github.com/ncihtan/htan-portal/issues/432
Remove "Level" dropdown on explore page
Test:
Old: 
https://htan-portal-nextjs-git-fork-leexgh-level-filter-htan.vercel.app/explore?selectedFilters=%5B%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+HMS%22%7D%5D&tab=file
New: 
https://htan-portal-nextjs-git-fork-leexgh-fix-level-filter-htan.vercel.app/explore?selectedFilters=%5B%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+HMS%22%7D%5D&tab=file
> Remove "Level" dropdown on explore page

- lib/dataSchemaHelpers.ts
We want the dependencies ordered alphabetically for the Data Standards page, but keep the default order for the Explore page table columns.
> Keep default order of required dependencies for explore page table columns

- data/htan-imaging-assets.json
HTAPP H&E thumbnails and minerva stories had a bright pink background due to the PhotometricInterpretation tag not being set to RGB. This is fixed here.
Also add a few WASHU H&E thumbnails that are missing (still more to do!)
> Update assets to included fixed HTAPP H&E images

- data/htan-imaging-assets.json
Were we have a Minerva story but are missing a thumbnail because of an error in Miniature (typically caused by blank or low contrast channels or a poorly formatted image) we can take one of the top level jpeg tiles as a thumbnail.
> Add minerva thumbnails

- components/FileTable.tsx
- components/filter/FilterControls.tsx
- lib/types.ts
Following up from #475 and to fully complete #468, I've taken a shot at renaming the `Download Source` filter to be `Data Access`.
I've left the underlying attribute name as `downloadSource` but updated the relevant `name`, `displayName` and `title` elements that showed up in a full repo search for `Download Source`.
> Rename 'Download Source' filter labels to 'Data Access'

- data/processSynapseJSON.ts
- lib/helpers.ts
Fix https://github.com/ncihtan/htan-portal/issues/504.
- update all 10x Visium Unknown Levels to be "Auxiliary"
- data access indicated as "Synapse" rather than "Coming Soon"
> Fix file level for 10x Visium Files

- data/tools_custom.json
Splitting ISB-CGC BigQuery Notebooks out into its own row in the tools catalog for easier accessibility
> Add ISB-CGC BQ Notebooks to tools page

- components/FileTable.tsx
- packages/data-portal-table/src/components/DataTableControls.tsx
Show button when no files are selected like this (was hidden before):
It wasn't entirely clear to people that "View Details" and the download button would download all the metadata, so make things more explicit with a button like:
and change "Details" text to:
> change download & metadata buttons

- components/Footer.tsx
- components/HtanNavbar.tsx
- components/PublicationTabs.tsx
Deprecate use of googlegroups, use Jira HTAN Help Desk link instead
> Update HTAN Help Desk links

- packages/data-portal-commons/src/lib/getCaseValues.ts
- packages/data-portal-commons/src/lib/types.ts
- packages/data-portal-explore/src/components/FileFilterControls.tsx
- packages/data-portal-utils/src/lib/types.ts
Fixing the #595 issue:
1. Created a filter by Organ Type filter on the organ dropdown box on the explore page.
2. Changed the original 'Organ' label in the dropdown box to the 'Organ Details'.
> add more coarse filter for organ type on the explore page

- packages/data-portal-explore/src/components/FileTable.tsx
> Include imaging data files in the CDS manifest

- components/PreReleaseBanner.tsx
"Open access (Level 3 and 4) files are currently unavailable through Synapse. The HTAN DCC will be resetting Synapse access controls on HTAN projects on Monday 22 April."
> Add banner re Synapse ACL issue

- packages/data-portal-commons/src/components/ExpandableText.tsx
- packages/data-portal-explore/src/lib/dataTableHelpers.tsx
Fix for #489 
Describe changes proposed in this pull request:
- Add a unique cell identifying value for state management, so that **_show more_** and **_show less_** act for that unique cell alone.
Screenshot:
Given:
Before:
After:
Notify reviewers:
@onursumer
> 🐛 Bug Fix: Show Less Button Incorrect Rendering

- data/processSynapseJSON.ts
- packages/data-portal-commons/src/lib/publicationHelpers.ts
- pages/publications/[id].tsx
- pages/publications/static_page_ids.json
Generate publication IDs as part of processedSynapseJSON. This hopefully fixes 5x errors in production
> Workaround for dynamic publication pages

- packages/data-portal-explore/src/components/FileTable.tsx
> Exclude therapy and therapy ids from file table columns

- data/syn_metadata.json
This is a quick workaround to remove a metadata file from the list.
We have to fix this on the synapse side because the file will come back when rerun the python importer script.
> Workaround to remove a metadata file

- next.config.js
This is a temporary redirect, which can be removed once the publication page is working
> Add HTAPP publication redirect

- packages/data-portal-explore/src/lib/helpers.ts
Fix #663
The organ count on the explore page is 22 as opposed to 21 shown on the home page because we filter out `Not Reported` (and `unknown`) there. We can do the same thing for explore page with some additional logic.
> Use coarse organ type when counting organs in the explore summary header

- packages/data-portal-explore/src/components/FileTable.tsx
Fix #688
Only added the below columns as metadata for now. We can add more columns if needed.
atlas_name, biospecimen, assay_name, level, data_file_id, parent_biospecimen_id, and parent_data_file_id.
When following [this import flow](https://docs.cancergenomicscloud.org/docs/import-from-a-drs-server#import-from-a-manifest-file) in [CGC](https://www.cancergenomicscloud.org/), the extra metadata will show up like:
> Add metadata to CGC file download manifest file

- packages/data-portal-explore/src/components/DataAvailabilityTable.tsx
> Do not show empty columns in Data Availability table

- README.md
- components/HomePage.tsx
- data/processSynapseJSON.log
- data/processSynapseJSON.ts
- lib/helpers.ts
- pages/static/data-updates.html
Fix #719
From: 
to:
Lots of images were actually not on CDS yet. We had incorrectly assumed several CDS releases were already available in https://github.com/ncihtan/htan-portal/pull/721). Prior to that the dropdown looked like this, so 6155 new files are now available from CDS (added to the release notes).
> Update CDS DRS mapping data

- data/processSynapseJSON.log
- data/processSynapseJSON.ts
- lib/helpers.ts
- packages/data-portal-commons/src/components/PublicationIcon.tsx
- packages/data-portal-commons/src/index.ts
- packages/data-portal-explore/src/components/AtlasTable.tsx
- packages/data-portal-explore/src/components/BiospecimenTable.tsx
- packages/data-portal-explore/src/components/CaseTable.tsx
- packages/data-portal-explore/src/components/Explore.tsx
- packages/data-portal-explore/src/components/ExploreTabs.tsx
- packages/data-portal-explore/src/components/FileTable.tsx
- packages/data-portal-explore/src/lib/dataTableHelpers.tsx
> Add Publication column for Cases, Biospecimen, and Files tabs

- packages/data-portal-explore/src/components/FileTable.tsx
As suggested by gen3 the gen3-client is more robust than the gen3 SDK. This PR updates instructions in the download modal. It should go alongside updated instructions in the docs.
> Update download modal instructions to use gen3-client 

- packages/data-portal-explore/src/components/PublicationTable.tsx
> Add minimal padding for publication titles

- packages/data-portal-explore/src/components/AtlasTable.tsx
> Order publication icons by date in atlas table

- packages/data-portal-explore/src/components/FileTable.tsx
- packages/data-portal-explore/src/components/fileTable.module.scss
Related to #783
BEFORE:
(File table)
(Metadata details)
AFTER:
(File table)
(Metadata details)
> Make sure the entire filename is visible in the tooltip
